CREATE TABLE [dbo].[CUSTOMERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](20) NOT NULL,
	[AGE] [int] NOT NULL,
	[ADDRESS] [char](25) NULL,
	[SALARY] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[PAYMENT]    Script Date: 07-Oct-18 9:41:56 PM ******/

CREATE TABLE [dbo].[PAYMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AMOUNT] [decimal](18, 2) NULL,
	[DATE] [date] NULL,
	[WORKSHEET_ID] [int] NULL,
 CONSTRAINT [PK_PAYMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



CREATE TABLE [dbo].[WORKSHEET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MONTH] [int] NOT NULL,
	[HOURS] [int] NOT NULL,
	[CUSTOMER_ID] [int] NULL,
 CONSTRAINT [PK_WORKSHEET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



ALTER TABLE [dbo].[CUSTOMERS]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMERS_CUSTOMERS] FOREIGN KEY([ID])
REFERENCES [dbo].[CUSTOMERS] ([ID])
GO

ALTER TABLE [dbo].[CUSTOMERS] CHECK CONSTRAINT [FK_CUSTOMERS_CUSTOMERS]
GO

ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_WORKSHEET] FOREIGN KEY([WORKSHEET_ID])
REFERENCES [dbo].[WORKSHEET] ([ID])
GO

ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_PAYMENT_WORKSHEET]
GO

ALTER TABLE [dbo].[WORKSHEET]  WITH CHECK ADD  CONSTRAINT [FK_WORKSHEET_CUSTOMERS] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMERS] ([ID])
GO

ALTER TABLE [dbo].[WORKSHEET] CHECK CONSTRAINT [FK_WORKSHEET_CUSTOMERS]
GO


