
INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Ramesh', 32, 'Ahmedabad', 150.00 );

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Khilan', 25, 'Delhi', 150.00 );

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('kaushik', 23, 'Kota', 200.00 );

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ('Chaitali', 25, 'Mumbai', 65.00 );

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ( 'Hardik', 27, 'Bhopal', 80.00 );

INSERT INTO CUSTOMERS (NAME,AGE,ADDRESS,SALARY)
VALUES ( 'Komal', 22, 'MP', 45.00 );


INSERT INTO WORKSHEET ( MONTH, HOURS, CUSTOMER_ID)
VALUES (1, 160 , 1);

INSERT INTO WORKSHEET ( MONTH, HOURS, CUSTOMER_ID)
VALUES (2, 156 , 1);

INSERT INTO WORKSHEET ( MONTH, HOURS, CUSTOMER_ID)
VALUES (1, 160 , 2);

INSERT INTO WORKSHEET ( MONTH, HOURS, CUSTOMER_ID)
VALUES (2, 80 , 2);



